[package]
name = "rust_bitcoin_tx_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
hex = "0.4.3"
assert_cmd = "2"
buffer = "0.1.9"
sha2 = "0.10"
